### ISSUE TITLE
old operator sdk is used

### ISSUE THREAD

**Issue by jacklu1024** [IBM/ibm-block-csi-operator#184]
Can anyone tell me why this very old operator sdk is still used? any plan to upgrade?
We have an operator wants to use CSI operator API but csi operator sdk version is too low to be compatible. thanks

github.com/operator-framework/operator-sdk v0.18.1

**Comment by roysahar-ibm** [comment]
@jacklu1024, We are working on upgrading the operator sdk. The updated sdk will be introduced on our next releases.

**Comment by jacklu1024** [comment]
Thanks, so is this targeted for CSI 1.7 release?

**Comment by roysahar-ibm** [comment]
@jacklu1024, we still did not close all the content for 1.7.0.

**Comment by jacklu1024** [comment]
Got it. thanks.
