### ISSUE TITLE
sidecars in use by IBM Block Storage CSI driver use old container registry and versions themselves are outdated

### ISSUE THREAD

**Issue by bh-tt** [IBM/ibm-block-csi-operator#374]
I found several issues while trying to deploy it:
 - the default registry uses k8s.gcr.io, which has frozen for over a year
 - the image versions are outdated, some by a few patches like csi-node-driver-registrar and some several major versions like csi-provisioner

I could find no documentation about which versions of these images this project is compatible with, but we can hardly leave them on outdated versions forever. Could some documentation about this be added?

**Comment by kasserater** [comment]
hi @bh-tt , not quite sure what you mean

we have several sidecars configured which are indeed hosted on k8s.gcr.io, but the operator is hosted on registry.connect.redhat.com and the subcomponents (driver and node) are hosted on quay.io

regarding the sidecar versions, we review the versions and update them from time to time as part of major releases only.
the current versions are those that the current release of the operator was tested and qualified for.

**Comment by bh-tt** [comment]
The k8s.gcr.io has been [frozen](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/) for a while now, so it might be good to update those domains to the new domain. 

Thank you for the response about the sidecar versions though, we will try to keep up with the sidecar versions as you update them.

**Comment by kasserater** [comment]
thank you @bh-tt for raising this issue. we will be sure to update the sidecar registry to the new one, and try to update the sidecar versions themselves in the next major release

**Comment by kasserater** [comment]
for future reference - https://kubernetes-csi.github.io/docs/sidecar-containers.html (links from this page point to new container registry and the latest versions)

**Comment by kasserater** [comment]
fixed as part of 89cab99183207a52e14a8705565f02136c4851fa (next 1.12.0 release)
