### ISSUE TITLE
How to setup Volume Expansion

### ISSUE THREAD

**Issue by hunghoang** [IBM/ibm-block-csi-operator#51]
Hi,
I'm using Kubernetes and setup this driver with IBM storage V5000. I wonder how to setup Volume Expansion because cannot find any document about this.
I try to resize volume on SAN but in my app, `df -h` still show the old volume size.
Please help, thanks

**Comment by 27149chen** [comment]
Volume Expansion is not supported yet, but it is in the plan. If it is an important feature in your field, please describe your requirement, we will consider to mark it higher.

**Comment by hunghoang** [comment]
My pod will be run out of storage suddenly or when I increase my storage and want to allocate more volume to pod.
For now, too many steps need to be taken:
- Change volume on storage management system
- Go to host and expand the mount volume
- Restart pod
We expect to have an automatically volume expansion feature for this driver
Thanks.

**Comment by erantzabari** [comment]
Currently the feature is planned for Q4/2020 delivery.
