### ISSUE TITLE
About volume mount: lib-modules

### ISSUE THREAD

**Issue by gianghn** [IBM/ibm-block-csi-operator#91]
Hi there, 

While we tried to upgrade from version 1.0 to version 1.2, we encounter a problem that said volume mount /lib/modules, folder does not exist. 

We use Rancher 2.4.5 and our node has Selinux enabled. 

Is there any clue to help ? 

Best regards,

Giang

**Comment by gianghn** [comment]
i've gone through the code, do we really need to mount the lib-modules volume ?

**Comment by erantzabari** [comment]
Currently, the CSI Operator implements the basic functionality and by so doesn't support HOT upgrade.
You should uninstall and reinstall the new version.

**Comment by erantzabari** [comment]
I am happy to announce that version 1.5.0 GAing this Thursday support seamless upgrade.
It should solve your issue.
